version: '3.8'

# name: 'mongodb_nestjs-final-test'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "${DATABASE_PORT}:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
